name: docx_template
description: A Docx template engine.
version: 0.3.2
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.2.1
  xml: ^5.3.1
  crypto: ^3.0.1
  path: ^1.8.1
  collection: ^1.15.0

